### ISSUE TITLE
Is the dataset still available?

### ISSUE THREAD

**Issue by bobwang-robotics** [lyft/nuscenes-devkit#12]
We have logged in the site but can't find any links to the dataset.

**Comment by Sajjadmanal** [comment]
You can download i from [here](https://storage.googleapis.com/lyft-av-dataset/data/v1.01-train.tar.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=cvprdataset-public%40cvprdataset-9fd3981b.iam.gserviceaccount.com%2F20190904%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20190904T054709Z&X-Goog-Expires=18000&X-Goog-SignedHeaders=host&X-Goog-Signature=b3ba93140c9e065bf033bb6ce061bab277fe80d096bdb7f9af97805b604506fe1b72595d610fd5fd00e1f668250e209f2088c9837baccc082124ffd0e2b2e70bd673a1af53fe1065ecb96671e871ffed1a2971a1c279f6256d9d3a155f56db0604dbb94d01d53ceb76f4e82f41742502a2c552dd19808c894dbe7ac9beecd943e7d46810d01cf293dbb356c2e5f2660d168fbdd7528ff660fee31405324b49fc72acd70094a367ff3ff4ba88cf644c23158b28ae0029b8da0c4b08bfe514f741277c7eeb48c229216ecac936b0cdb0fd81427af326e538bf4d7d80512885e7451659962b43aa769f6f38794b4f715bbd71825365a0a34531497df264634675c8).

**Comment by ternaus** [comment]
should work now. 

Alternatively, you can download it at https://www.kaggle.com/c/3d-object-detection-for-autonomous-vehicles
