### ISSUE TITLE
Unable to load dataset

### ISSUE THREAD

**Issue by Sajjadmanal** [lyft/nuscenes-devkit#14]
Hi,
I downloaded the  dataset successfully but not able to load it.
When I try:
```
# Load the SDK
%matplotlib inline
from nuscenes.nuscenes import NuScenes

# Load the dataset
# Adjust the dataroot parameter below to point to your local dataset path.
# Note that using "~" for your home directory typically won't work here, thus specify the complete pathname.
# The correct dataset path contains at least the following four folders (or similar): images, lidar, maps, v1.0-mini
# In case you didn't download the 'v1.0-mini' version of the dataset, also adjust the version parameter below.
level5data = NuScenes(version='v1.01-train', dataroot=r'D:\Projects\lidar\dataset lidar\v1.01-train', verbose=True)
```

It gives me the below error:

> ======
> Loading NuScenes tables for version v1.01-train...
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-9-34e61ee63cce> in <module>
>       8 # The correct dataset path contains at least the following four folders (or similar): images, lidar, maps, v1.0-mini
>       9 # In case you didn't download the 'v1.0-mini' version of the dataset, also adjust the version parameter below.
> ---> 10 level5data = NuScenes(version='v1.01-train', dataroot=r'D:\Projects\lidar\dataset lidar\v1.01-train', verbose=True)
> 
> ~\Desktop\lyftml\python-sdk\nuscenes\nuscenes.py in __init__(self, version, dataroot, verbose, map_resolution)
>      61 
>      62         # Explicitly assign tables to help the IDE determine valid class members.
> ---> 63         self.category = self.__load_table__('category')
>      64         self.attribute = self.__load_table__('attribute')
>      65         self.visibility = self.__load_table__('visibility')
> 
> ~\Desktop\lyftml\python-sdk\nuscenes\nuscenes.py in __load_table__(self, table_name)
>      97     def __load_table__(self, table_name) -> dict:
>      98         """ Loads a table. """
> ---> 99         with open(osp.join(self.table_root, '{}.json'.format(table_name))) as f:
>     100             table = json.load(f)
>     101         return table
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\lidar\\dataset lidar\\v1.01-train\\v1.01-train\\category.json'

**Comment by apassi99** [comment]
I am not sure about this but can you try passing the file name like this: 'D:\\Projects\\lidar\\dataset lidar\\v1.01-train\\v1.01-train

**Comment by Sajjadmanal** [comment]
@apassi99 I tried but it didn't work.

**Comment by ternaus** [comment]
None of us is using windows, it is really hard to reproduce this bug. Not sure when we will be able to address it.
