### ISSUE TITLE
A bug in render_scene function

### ISSUE THREAD

**Issue by pyaf** [lyft/nuscenes-devkit#22]
Hi, 

The [render_scene](https://github.com/lyft/nuscenes-devkit/blob/master/lyft_dataset_sdk/lyftdataset.py#L1130) function uses cv2.VideoWriter [here](https://github.com/lyft/nuscenes-devkit/blob/master/lyft_dataset_sdk/lyftdataset.py#L1183) the first argument of which should be a string not a Path instance due to which it is throwing type error.

So, it should be 
`out = cv2.VideoWriter(str(out_path), fourcc, freq, canvas.shape[1::-1])`

**Comment by ternaus** [comment]
Fixed.
