### ISSUE TITLE
Some details about the competition

### ISSUE THREAD

**Issue by Tai-Wang** [lyft/nuscenes-devkit#30]
Hi,

I'd like to make sure whether all the categories detection precision/mAP will be calculated. (Nuscenes selected only 10 interested categories from their annotations.) Besides, do the prediction of attribute and velocity not considered right now?

Thanks a lot!

**Comment by ternaus** [comment]
I can answer both questions here, but could you please repeat this question at the Kaggle forum, other people may have a similar one.
