### ISSUE TITLE
Front LiDAR point cloud incorrectly rendered in tutorial?

### ISSUE THREAD

**Issue by opoppo** [lyft/nuscenes-devkit#44]
![下载](https://user-images.githubusercontent.com/11325853/65397760-45cfb400-dde5-11e9-8ef1-327ae93e6515.png)
In the jupyter notebook tutorial, it seems that the point cloud from both LIDAR_FRONT_RIGHT and LIDAR_FRONT_LEFT do not match the annotated boxes.
From the example rendered picture above, it looks like the point clouds are somehow flipped with respect to a 45° or 135° axis, but even after i flip them back, the point cloud still suffer from distortions.   
![22](https://user-images.githubusercontent.com/11325853/65397948-a01d4480-dde6-11e9-9be8-5312bae1ed38.png)
![33](https://user-images.githubusercontent.com/11325853/65397949-a14e7180-dde6-11e9-94b6-60e6edbcaedb.png)
Guessing the transformation between coordinates or calibration parameters got some minor bugs there?  Any suggestions?

**Comment by rkesten** [comment]
Thank you for flagging this! The issue does not occur anymore with the v1.02 dataset (which is used in the Kaggle competition). Therefore, I'm closing the issue.
