### ISSUE TITLE
Bug in Intersection over Union calculations

### ISSUE THREAD

**Issue by RustemIskuzhin** [lyft/nuscenes-devkit#47]
I find that predicting 3d boxes with increased lengths and widths (x100 from original) somehow change score from 0.233 to 0.408. I think it should bug in Intersection over Union calculations.

**Comment by ternaus** [comment]
Thank you! We will look into this.

**Comment by ternaus** [comment]
There was a bug in the metric implementation at Kaggle. Was fixed. Everything should be fine now.
