### ISSUE TITLE
While installing using pip install -U lyft_dataset_sdk in virtual environment getting this error.      

### ISSUE THREAD

**Issue by rajeev921** [lyft/nuscenes-devkit#49]

**Comment by rajeev921** [comment]
ERROR: Could not find a version that satisfies the requirement black (from lyft-dataset-sdk==0.0.8) (from versions: none) ERROR: No matching distribution found for black (from lyft-dataset-sdk==0.0.8)

**Comment by ternaus** [comment]
What error do you get, when you run 

`pip install black` ?

**Comment by rajeev921** [comment]
pip install black
Collecting black
  ERROR: Could not find a version that satisfies the requirement black (from versions: none)
ERROR: No matching distribution found for black

**Comment by pyaf** [comment]
@rajeev921 which python version are you using?

**Comment by rajeev921** [comment]
3.5.2

**Comment by pyaf** [comment]
Black requires 3.6.0+
See here: https://github.com/psf/black#installation

**Comment by rajeev921** [comment]
> Black requires 3.6.0+
> See here: https://github.com/psf/black#installation

Thank you!
Successfully installed now.
