### ISSUE TITLE
Why the two classes ?

### ISSUE THREAD

**Issue by yuqli** [lyft/nuscenes-devkit#5]
Thanks for open sourcing the tools. Not sure where to post Q&A but I'm just wondering why we have a `nuscenes` class and a `nuscenesExplorer` class? Many functions seem to be similar e.g. `render_sample_data` in `nuscenes` calls the `render_sample_data` function in the explorer class.

**Comment by Dawars** [comment]
You should ask the nuscenes guys about this, this is a "fork" of their devkit
https://github.com/nutonomy/nuscenes-devkit/issues

**Comment by yuqli** [comment]
Thanks @Dawars for the link. I think I figured it out : `nuscenes` is for data retrieving and the explorer class is for visualization.
