### ISSUE TITLE
Invalid lidar point file

### ISSUE THREAD

**Issue by DaHaiHuha** [lyft/nuscenes-devkit#50]
During handle with the lidar point cloud, the sample(which token is 
'9cb04b1a4d476fd0782431764c7b55e91c6dbcbc6197c3dab3e044f13d058011')
has a wrong dimention of lidar point file. The sensor channel is LIDAR_TOP.
When I do 
`scan = np.fromfile(str(file_name), dtype=np.float32)
        points = scan.reshape((-1, 5))[:, : cls.nbr_dims()]`
the the error orrured:
`ValueError: cannot reshape array of size 265728 into shape (5)`

**Comment by muzi2045** [comment]
with this different lidar bin file, I can just try to handle it by this:
```
spec_lidar_path_1 = '/home/muzi2045/Downloads/lyft_dataset/v1.01-train/lidar/host-a011_lidar1_1233090652702363606.bin'
        if str(lidar_path) != spec_lidar_path_1:
            print("lidar_path:", str(lidar_path))
            points = np.fromfile(str(lidar_path), dtype=np.float32).reshape((-1, 5))[:, :4]
            points[:, 3] /= 255
        else:
            points = np.fromfile(str(lidar_path), dtype=np.float32).reshape((-1, 4))[:, :4]
            points[:, 3] /= 255

```

**Comment by muzi2045** [comment]
looks like some data wrong....
![snapshot](https://user-images.githubusercontent.com/12984898/66797428-5505d580-ef3d-11e9-83ce-7bd244c71c8d.png)

**Comment by rkesten** [comment]
Hi! Please make sure you work with the most recent (1.02) version of the dataset. This problem does not occur there anymore.

**Comment by muzi2045** [comment]
Is there any correct single lidar file  to replace this wrong lidar data file?
Just Don't want to download the whole the dataset again...
@rkesten

**Comment by rkesten** [comment]
Sorry, but there is no incremental update to 1.02. There are several other issues fixed as well.

**Comment by HH0314** [comment]
I just tried to download the dataset from (https://level5.lyft.com/dataset/) again but the version of the training dataset was still v1.01. Where can I download the most recent version? @rkesten

**Comment by rkesten** [comment]
@HH0314 good point, that link isn't up to date. This should be fixed by tomorrow, so that v1.02 will be available via that site. Sorry for the confusion!

**Comment by explorer359** [comment]
points = scan.reshape((-1, 5))[:, : cls.nbr_dims()]
ValueError: cannot reshape array of size 265728 into shape (5)

Hey @rkesten  i am also facing same issue, by downloading V1.02 can i resolve this issue?

**Comment by hcyoo93** [comment]
points = scan.reshape((-1, 5))[:, : cls.nbr_dims()]
ValueError: cannot reshape array of size 265728 into shape (5)

@rkesten @explorer359 
I am facing the same issue.

I cannot find the version of dataset, but I am pretty sure it is the latest one
(downloaded in July2020 from [https://self-driving.lyft.com/level5/download/])
