### ISSUE TITLE
Inaccurate calibration matrix

### ISSUE THREAD

**Issue by breizhtaz** [lyft/nuscenes-devkit#67]
When fusing lidar points from all 3 sources I noticed while using the dataset v1.01 that you get artifacts.
The calibration matrix for one of the sensors is not correct. This happens for the a101 sequence but not for the a102 (first 2 images below from a101, following images from a102).

Is this calibration issue fixed in the v1.02 of the dataset? I'd like to know before I download it entirely again.

Thanks!

![a101_1](https://user-images.githubusercontent.com/15742453/68327237-d0acfb00-0081-11ea-91a1-d2bf4ac19ba8.png)
![a101_2](https://user-images.githubusercontent.com/15742453/68327238-d0acfb00-0081-11ea-8a5c-9f624b2b3ec2.png)
![a102_1](https://user-images.githubusercontent.com/15742453/68327239-d1459180-0081-11ea-97e0-951316745d91.png)
![a102_2](https://user-images.githubusercontent.com/15742453/68327243-d1459180-0081-11ea-9ba4-975a8f54cbfb.png)

**Comment by Dawars** [comment]
Did someone get the same results? What's the status of this issue?

**Comment by rkesten** [comment]
Hi, there were some calibration issues in the v1.01 dataset which were resolved in the v1.02 version. This issue is not present in the v1.02 dataset anymore.
