### ISSUE TITLE
How to distinguish between BETA_V0 and BETA_PLUS_PLUS

### ISSUE THREAD

**Issue by maxjaritz** [lyft/nuscenes-devkit#8]
Hello,
Is it possible from the meta data to know if the current scene is from a BETA_V0 vehicle or a BETA_PLUS_PLUS vehicle? I want to use the LIDAR_TOP and am curious about how many scenes have 40 beam lidar and how many scenes 64 beam lidar.

Thanks

**Comment by Dawars** [comment]
https://github.com/lyft/nuscenes-devkit/issues/4#issuecomment-519822737

**Comment by maxjaritz** [comment]
I guess, a safe way is to check for image size, as it is easier than counting the lidar beams. BETA_V0 has  1224x1024 and BETA_PLUS_PLUS has 1920x1080.

**Comment by YurongYou** [comment]
Hi! But I found no sample which has 1920x1080 resolution images
